export {setGameParams, checkMatch, showClick, addMatch, overlayId, imageViewId} from './game.js'
export {Loci, stickersNames} from './loci.js'
export {addToId, addClass, removeClass, shuffle, getId, removeAnimation, removeAddClasses} from './utils.js'
export {lociBack} from '../../data/locidata.js'
export {stickers} from '../../data/data.js'